name: docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Build the Docker image
         echo ${{ secrets.PASSWORD}} | sudo docker build . -t website
         echo ${{ secrets.PASSWORD}} | sudo docker run -itd  -p5000:80 website:latest
